fix how to review
Artificial-Intelligence-FHB-TDU/KI-Vorlesung pull request #188
Opened 2022-10-01 15:50 UTC by FinnAmini

Kleine Änderungen an dem How-To-Feedback Abschnitt des FAQ's

closes #187

2022-10-01 17:12 UTC, cagix requested changes
@FinnAmini Danke fürs Drüberschauen. Hier noch ein paar Fixes für Deinen Fix :)

Hast Du ein paar Screenshots oder so, die ich hier einbauen könnte? Kannst Du gern in eine Word-Datei machen und diese hier im PR in einem Kommentar hochladen oder so, dann baue ich das in den Text ein. Wäre vielleicht ganz nett, weil damit vermutlich noch keiner gearbeitet hat ...

2022-10-01 17:12 UTC, cagix commented on markdown/org/faq.md
> +Da das Feedback anonymisiert ist, müssen sie dabei auf die Poster achten
```suggestion
Da das Feedback anonymisiert ist, müssen Sie dabei auf die Poster achten
```

2022-10-01 17:12 UTC, cagix commented on markdown/org/faq.md
> +mal die Lösung eines Teams zuweist, da jedes Mitglied einer Gruppe die Lösung einzeln
```suggestion
Mal die Lösung Ihres Teams zuweist, da jedes Mitglied einer Gruppe die Lösung einzeln
```

2022-10-01 17:12 UTC, cagix commented on markdown/org/faq.md
> +hochladen muss. In diesem Fall vergeben Sie bitte zwei mal das gleiche Feedback.
```suggestion
hochladen muss. In diesem Fall vergeben Sie bitte zwei Mal das gleiche Feedback ("eigenes Team").
```

2022-10-03 09:03 UTC, FinnAmini commented on markdown/org/faq.md
> +mal die Lösung eines Teams zuweist, da jedes Mitglied einer Gruppe die Lösung einzeln
Ich glaube das passt so, oder? Neben der Bewertung des eigenen Teampartners kann ja auch passieren, dass man zwei mal die gleiche Lösung eines anderen Teams bewerten muss, oder nicht?

2022-10-03 09:04 UTC, FinnAmini commented
Ich habe kleine Teile des How-To-Feedbacks umgeschrieben und die wichtigsten Punkte mit Screenshots ergänzt. Ich hoffe das passt so :)

2022-10-03 11:03 UTC, cagix commented on markdown/org/faq.md
> +mal die Lösung eines Teams zuweist, da jedes Mitglied einer Gruppe die Lösung einzeln
Ah, Du hast recht! Ich hatte beim Lesen an das eigene Team gedacht, aber das ist eigentlich Quatsch: IlIAS würde ja mir maximal meinen Teampartner zuweisen und nicht auch noch meine eigene Abgabe. Aber bei "fremden" Teams kann es gut passieren, dass ich zweimal das selbe Team zugewiesen kriege. Passt.

2022-10-03 11:18 UTC, cagix reviewed
@FinnAmini Ich hab mal ein paar kleinere Verbesserungen eingebaut (Formulierung, interne Formatierung).

Für mich ist noch eine Lücke zwischen Bild 3 und 4. Wie sieht das denn aus, wenn ich auf "Bearbeiten" klicke? Oder hängt das von der Art des Feedbacks ab und man kann hier keine allgemeinen Bilder machen?

2022-10-03 11:25 UTC, cagix commented
@FinnAmini Oh, und ich habe die Bilder als .png konvertiert und mit max. 1200px Breite. (Irgendwas in der Toolchain scheint keine .jpg zu mögen, und 1900px braucht hier keiner - es ist ja kaum was drauf auf den Bildern ;)

2022-10-03 12:37 UTC, FinnAmini commented
> @FinnAmini Ich hab mal ein paar kleinere Verbesserungen eingebaut (Formulierung, interne Formatierung).
> 
> Für mich ist noch eine Lücke zwischen Bild 3 und 4. Wie sieht das denn aus, wenn ich auf "Bearbeiten" klicke? Oder hängt das von der Art des Feedbacks ab und man kann hier keine allgemeinen Bilder machen?

Du hast Recht, ich habe da mal ein weiteres Image ergänzt, welches den Ablauf hoffentlich verständlicher macht. Die Genaue Ansicht ist tatsächlich abhängig davon, wie nachher der Kriterienkatalog gestaltet wird, das Prinzip ist jedoch immer das gleiche.

2022-10-03 12:39 UTC, FinnAmini commented
> @FinnAmini Oh, und ich habe die Bilder als .png konvertiert und mit max. 1200px Breite. (Irgendwas in der Toolchain scheint keine .jpg zu mögen, und 1900px braucht hier keiner - es ist ja kaum was drauf auf den Bildern ;)

Perfekt, ja das stimmt ^^ - ich war mir auch nicht ganz sicher, ob es wirklich nötig ist immer den gesamtem Screen abzubilden, oder nur den jeweiligen relevanten Bereich..

2022-10-03 12:53 UTC, cagix approved these changes
@FinnAmini mange takk!

2022-10-03 12:53 UTC, merged